### PR TITLE
Generate arrow images of variable size

### PR DESCRIPTION
**Pull request by katspaugh**
Hi Jonathan!

I would like to have arrows of size 12x24 (to match the Monaco font at height 18), so I thought it would be nice to make these arrows' size dependent on the mode-line font-face.

This is the first step – a function to generate XPM templates. Please confirm whether it is an acceptable direction of development.

### CODE REVIEW

**Comment by katspaugh** [comment]
cc @WHOISJohnGalt

**Comment by ghost** [comment]
Yeah, this is much better than my dumb pull request.

**Comment by jonathanchu** [comment]
This looks great at first glance @katspaugh!  Let me take a deeper dive into this this weekend and I'll get back to you /cc @WHOISJohnGalt 

Thanks so much!

**Comment by katspaugh** [comment]
It seems @winterTTr has already written some well structured utilities for generating triangles in the mode-line: https://github.com/winterTTr/emacs-of-winterTTr/blob/master/.emacs.d/wttr-config/wttr-mode-line.el

Doh, the same issue has also been already addressed in the proposed version 2 from #13.

**Comment by jonathanchu** [comment]
@katspaugh When you get a chance, would you mind leaving or emailing me your full name so I can add to AUTHORS?  If not, I'll just add your GitHub handle. :)

**Comment by katspaugh** [comment]
Hey Jonathan! Thanks! Glad you had time to review it.

Username is OK, thank you.

**Pull request merged**
